// <auto-generated />
using System;
using Alfred2.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Alfred2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618194250_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Alfred2.Models.BloqueoAgenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FinUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "InicioUtc");

                    b.ToTable("Bloqueos");
                });

            modelBuilder.Entity("Alfred2.Models.Conversacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("ExternoThreadId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroPacienteE164")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NumeroRemitenteE164")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UltimoMensajeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("MedicoId", "PacienteId", "Canal");

                    b.ToTable("Conversaciones");
                });

            modelBuilder.Entity("Alfred2.Models.DisponibilidadSemanal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int>("DuracionTurnoMin")
                        .HasColumnType("integer");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "DiaSemana");

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("Alfred2.Models.IntegracionCalendario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenEnc")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpiraUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternoAccountId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RefreshTokenEnc")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "Proveedor");

                    b.ToTable("Integraciones");
                });

            modelBuilder.Entity("Alfred2.Models.Medico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoResponderHabilitado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("EstadoVerificacion")
                        .HasColumnType("integer");

                    b.Property<string>("Matricula")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("ModificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("TelefonoE164")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TextoAutoResponder")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ZonaHorariaIana")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("Alfred2.Models.Mensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direccion")
                        .HasColumnType("integer");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EntregadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EnviadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternoMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LeidoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("ModificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Plantilla")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Texto")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId", "EnviadoUtc");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("Alfred2.Models.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("Notas")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TelefonoE164")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "TelefonoE164")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Alfred2.Models.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DuracionMin")
                        .HasColumnType("integer");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "Nombre")
                        .IsUnique();

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Alfred2.Models.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FinUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Moneda")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("NotasInternas")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<int>("Origen")
                        .HasColumnType("integer");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PrecioAcordado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("ServicioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("MedicoId", "InicioUtc");

                    b.HasIndex("MedicoId", "InicioUtc", "Estado");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Alfred2.Models.TurnoSyncCalendario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("ExternoCalendarId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExternoEventId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("IntegracionCalendarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TurnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("UltimoSyncUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IntegracionCalendarioId");

                    b.HasIndex("TurnoId", "IntegracionCalendarioId")
                        .IsUnique();

                    b.ToTable("TurnoSincronizaciones");
                });

            modelBuilder.Entity("Alfred2.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("GoogleSub")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("ModificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Alfred2.Models.BloqueoAgenda", b =>
                {
                    b.HasOne("Alfred2.Models.Medico", "Medico")
                        .WithMany("Bloqueos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Alfred2.Models.Conversacion", b =>
                {
                    b.HasOne("Alfred2.Models.Medico", "Medico")
                        .WithMany("Conversaciones")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alfred2.Models.Paciente", "Paciente")
                        .WithMany("Conversaciones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Alfred2.Models.DisponibilidadSemanal", b =>
                {
                    b.HasOne("Alfred2.Models.Medico", "Medico")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Alfred2.Models.IntegracionCalendario", b =>
                {
                    b.HasOne("Alfred2.Models.Medico", "Medico")
                        .WithMany("Integraciones")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Alfred2.Models.Medico", b =>
                {
                    b.HasOne("Alfred2.Models.User", "User")
                        .WithOne("Medico")
                        .HasForeignKey("Alfred2.Models.Medico", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Alfred2.Models.Mensaje", b =>
                {
                    b.HasOne("Alfred2.Models.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("Alfred2.Models.Paciente", b =>
                {
                    b.HasOne("Alfred2.Models.Medico", "Medico")
                        .WithMany("Pacientes")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Alfred2.Models.Servicio", b =>
                {
                    b.HasOne("Alfred2.Models.Medico", "Medico")
                        .WithMany("Servicios")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Alfred2.Models.Turno", b =>
                {
                    b.HasOne("Alfred2.Models.Medico", "Medico")
                        .WithMany("Turnos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alfred2.Models.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alfred2.Models.Servicio", "Servicio")
                        .WithMany("Turnos")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Medico");

                    b.Navigation("Paciente");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Alfred2.Models.TurnoSyncCalendario", b =>
                {
                    b.HasOne("Alfred2.Models.IntegracionCalendario", "IntegracionCalendario")
                        .WithMany("Sincronizaciones")
                        .HasForeignKey("IntegracionCalendarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfred2.Models.Turno", "Turno")
                        .WithMany("Sincronizaciones")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegracionCalendario");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Alfred2.Models.Conversacion", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("Alfred2.Models.IntegracionCalendario", b =>
                {
                    b.Navigation("Sincronizaciones");
                });

            modelBuilder.Entity("Alfred2.Models.Medico", b =>
                {
                    b.Navigation("Bloqueos");

                    b.Navigation("Conversaciones");

                    b.Navigation("Disponibilidades");

                    b.Navigation("Integraciones");

                    b.Navigation("Pacientes");

                    b.Navigation("Servicios");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Alfred2.Models.Paciente", b =>
                {
                    b.Navigation("Conversaciones");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Alfred2.Models.Servicio", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Alfred2.Models.Turno", b =>
                {
                    b.Navigation("Sincronizaciones");
                });

            modelBuilder.Entity("Alfred2.Models.User", b =>
                {
                    b.Navigation("Medico");
                });
#pragma warning restore 612, 618
        }
    }
}
